version: 2.1
jobs:
  Land-Reg:
    docker:
      - image: cimg/python:3.11.2-node
    steps:
      - checkout
      - run:
          name: Testing A land reg
          command: |
            poetry shell
            poetry install
            poetry run pytest test_land_reg_two.py
workflows:
  TestingLandReg:
    jobs:
      - Land-Reg